### DISCUSSION TITLE
Running multiple sidekiq on local development machine

### DISCUSSION THREAD

**Discussion by StephyMilkyCat** [sidekiq/sidekiq#4979] [General]
I am running 2 workers locally by executing the following command
```
bundle exec sidekiq -C config/sidekiq/standard.yml;
bundle exec sidekiq -C config/sidekiq/medium.yml;
```
when I sending out some sidekiq jobs, the latest worker I started will take over the process
e.g. if I start `standard` and then start `medium`, then `medium` will take over the jobs, no way for me to use `standard` one; once I shutdown `medium`, then standard will take over the jobs; and vice versa...

Is there any way to specify a certain sidekiq process to be worked with?

**Comment by mperham** [comment]
If you want to run multiple Sidekiq processes, use a process manager. For instance, use [foreman](https://github.com/ddollar/foreman).

**Comment by StephyMilkyCat** [comment]
@mperham but how can I assign a specific job (by condition) to a specific sidekiq process?

**Comment by mperham** [comment]
Through a queue. You push a job to a queue and define the queues that each process fetches from.

**Comment by StephyMilkyCat** [comment]
@mperham 
Thank you. I will look at it, may raise further question if necessary.

**Comment by nayoothant** [comment]
> I am running 2 workers locally by executing the following command
> 
> ```
> bundle exec sidekiq -C config/sidekiq/standard.yml;
> bundle exec sidekiq -C config/sidekiq/medium.yml;
> ```
> 
> when I sending out some sidekiq jobs, the latest worker I started will take over the process e.g. if I start `standard` and then start `medium`, then `medium` will take over the jobs, no way for me to use `standard` one; once I shutdown `medium`, then standard will take over the jobs; and vice versa...
> 
> Is there any way to specify a certain sidekiq process to be worked with?

@StephyCat  
@mperham 
I am using docker and I have the same problem as you did.
```
  sidekiq1:
    <<: *app_base
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq1.yml"]
    ports: []
    depends_on: []
    tty: false
    stdin_open: false

  sidekiq2:
    <<: *app_base
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq2.yml"]
    ports: []
    depends_on: []
    tty: false
    stdin_open: false
```
Can you please tell me how did you solve this?
