### DISCUSSION TITLE
With the release of 7.0 and Capsules, will sidekiq.yml support capsule creation/configuration?

### DISCUSSION THREAD

**Discussion by BobbyMcWho** [sidekiq/sidekiq#5546] [Q&A] [answered]
We run Enterprise & Sidekiqswarm, with 3 separate configs for different queue sets. I want to run a large async searchkick reindex, and the number of jobs will be in the thousands generated all at once by searchkick. Rather than saturate all of our 'general' processes/threads w/ them, I'd like to reduce the concurrency. My initial thought is to just use sidekiq-ent concurrent rate limiter, but that will still saturate the threads until the locks/retry scheduling shakes itself out. 

Sidekiq 7 w/ capsules sounds like a great solution, but I am struggling to figure out how I can configure the capsule on only 1 of 3 server configs (since we pass them as file configs).

**Comment by mperham** [comment]
Today, sidekiq.yml and `-C` only work with the default capsule. Other capsules must be configured in Ruby.

**Comment by nateberkopec** [comment, marked as answer]
Yes. https://github.com/mperham/sidekiq/pull/5547 💥

**Reply by BobbyMcWho** [reply]
Be the change you want to see right 😅

**Reply by bert-mccutchen** [reply]
Hey @mperham, can you add documentation for this feature to the wiki please?

**Reply by mperham** [reply]
I don’t document things which I don’t endorse. Capsules should be configured in Ruby.

**Reply by bert-mccutchen** [reply]
**Why should Sidekiq Capsules only be configured in Ruby?**

I'd like to hear your thoughts as to why you don't endorse configuring Capsules in Ruby via YAML. Especially since the introduction of Capsules created the concept of a ["default" Capsule](https://github.com/sidekiq/sidekiq/blob/d12fa084984fccec3dfb3771ac6a8ef525a13bd9/lib/sidekiq/config.rb#L106-L108), which is configured in Ruby via YAML.

Initializing other Capsules via YAML only makes sense. If anything it would make more sense to align all Capsules, including the default, to use the same implementation.

Example:
```yaml
capsules:
  default:
    concurrency: 12
    queues:
      - default
  priority:
    concurrency: 4
    queues:
      - events
      - mailers
```

Also, unless there are other undocumented features, initializing via Ruby alone does not gain the benefit of setting different concurrency amounts based on the environment. Obviously you could manually check what environment you're running in Ruby. Though, that seems like overkill when the capability already exists when using YAML configurations.

Example:
```yaml
capsules:
  default: &default
    concurrency: 16
    queues:
      - default
  priority: &priority
    concurrency: 8
    queues:
      - events
      - mailers

production:
  capsules:
    default:
      <<: *default
      concurrency: 32
    priority:
      <<: *priority
      concurrency: 16
```
