### ISSUE TITLE
Clustered rate limiters

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5800]
If using many thousands or even millions of rate limiters, it can be hugely beneficial to use a Cluster as the rate limiter storage in order to scale beyond one Redis instance. We can modify the rate limiter data model to take advantage of "Hash tags" in the cluster spec[^0] to ensure all keys for a limiter X resides on the same Redis instance within the cluster. This ensures that any related Lua script will have local data to work with when running within Redis.

Note that the Web UI functionality is not cluster-friendly; it uses SCAN to look for all limiters to list but but this will only scan one Redis instance. Nevertheless, for the largest users this limitation on visibility (who's using the Web UI to look at millions of limiters??) is a reasonable trade off to enable massive scale.

cc @sj26 

[^0]: https://redis.io/docs/reference/cluster-spec/

**Comment by mperham** [comment]
This is a harder change than I first thought; I don't have a Redis cluster to test against so I need to create some non-trivial test infrastructure first.

**Comment by mperham** [comment]
- [ ] Concurrent - uses multiple keys, needs hash slot
- [ ] Bucket - uses multiple keys, needs hash slot
- [x] Window - only uses one key, naturally cluster-safe
- [x] Leaky - only uses one key, naturally cluster-safe
- [x] Points - only uses one key, naturally cluster-safe

**Comment by mperham** [comment]
Good blog post on this subject: https://redis.com/blog/redis-clustering-best-practices-with-keys/

**Comment by jgaskins** [comment]
> Note that the Web UI functionality is not cluster-friendly; it uses SCAN to look for all limiters to list but but this will only scan one Redis instance.

The way I implemented this in my Crystal Redis library was to have [`Cluster#scan_each` run `scan_each` across one replica of each shard](https://github.com/jgaskins/redis/blob/v0.6.1/src/cluster.cr#L205-L207). IIRC the Ruby Redis library [doesn't have that](https://github.com/redis/redis-rb/blob/e4f5299aa0109d1334564f20ae8522866ef554e9/cluster/lib/redis/cluster/client.rb), and it may not be a _great_ idea at a large-enough scale, but it could still work for this purpose.

**Comment by mperham** [comment]
@jgaskins Yep. The Pro Web UI already has a sharding support; the customer could set up the Web UI with each cluster member as a shard.

**Comment by sj26** [comment]
If it's helpful, I started a cluster for testing with a Procfile containing:

```
redis-node-1: cd tmp/redis-cluster/node-1 && redis-server --port 7001 --cluster-enabled yes --cluster-config-file node.conf --cluster-node-timeout 5000 --appendonly yes
redis-node-2: cd tmp/redis-cluster/node-2 && redis-server --port 7002 --cluster-enabled yes --cluster-config-file node.conf --cluster-node-timeout 5000 --appendonly yes
redis-node-3: cd tmp/redis-cluster/node-3 && redis-server --port 7003 --cluster-enabled yes --cluster-config-file node.conf --cluster-node-timeout 5000 --appendonly yes
```

and then running:

```
redis-cli --cluster create 127.0.0.1:700{1,2,3} --cluster-replicas 0
```

The config files mentioned do not need to exist, they are written by redis during the cluster setup command.

In CI, we use a docker-compose containing:

```yaml
  # This creates a redis cluster with 3 master nodes and 3 replicas, as
  # recommended in https://redis.io/docs/manual/scaling.
  # It's likely the replicas aren't necessary in test environments but I don't
  # see any harm including them just to make CI that little bit closer to
  # production.
  #
  # Clustered redis expects to have a public IP address and port that's used
  # by the other nodes as well as clients. This is fiddly to get right in
  # docker so we use a third party docker image that does that work for us.
  # See https://github.com/bitnami/bitnami-docker-redis-cluster.
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
```
