### ISSUE TITLE
The job stays queued while there are no any othe jobs in queue

### ISSUE THREAD

**Issue by hww** [sidekiq/sidekiq#5840]
The job task in the low priority queue stays 'cueued' and no any progress. What can cause such behavior? There are no errors or exceptions in the log.

Ruby version: ruby 3.2.0 
Rails version: Rails 7.0.4.2
Sidekiq / Pro / Enterprise version(s):  Sidekiq 6.5.8

The initializer, sidekiq.yml
```
# config/sidekiq.yml---
:verbose: true
:concurrency: <%=ENV.fetch("RAILS_MAX_THREADS") { 7 } %>
:timeout: 10

:queues:
  - [default, 2]
  - [low, 1]
  - [high, 4] # high priority

:scheduler:
  :schedule:
    DashboardUpdaterJob:
      cron: '0,10,20,30,40,50 * * * *'
      class: DashboardUpdaterJob
      args: []
      description: "Update user's dasboards"
      queue: low
      enabled: false
    BoardTaskActivatorJob:
      cron: '0,10,20,30,40,50 * * * *'
      class: BoardTaskActivatorJob
      args: []
      description: "Activate board tasks"
      queue: low
      enabled: false
    SoftBuildJob:
      cron: '0,10,20,30,40,50 * * * *'
      class: SoftBuildJob
      args: [{dry_run:true}]
      description: "Activate board tasks"
      queue: low
      enabled: false
    SoftRsyncJob:
      cron: '0,10,20,30,40,50 * * * *'
      class: SoftRsyncJob
      args: [{dry_run:true}]
      description: "Activate board tasks"
      queue: low
      enabled: false
```
