### ISSUE TITLE
Create example Github actions YML for usage with Sidekiq Pro/Ent

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5906]
Does anyone have a sanitized GitHub Actions YML they use for CI with Sidekiq Pro or Enterprise they'd like to share? I'd like to show people how to reference their gem server credentials in a safe and idiomatic fashion.

For that matter, any integration with popular services (fly, render, heroku, other CI providers) are welcome.

Any contributions would go in the `examples/` directory as a reference.

**Comment by mperham** [comment]
Customer was able to get their workflow working by creating a Repository secret and then referencing it at the `setup-ruby` step.

```yml
- name: Setup Ruby
  uses: ruby/setup-ruby@v1
    env:
      BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
    with:
      bundler-cache: true
```
