### ISSUE TITLE
Run Ansible Playbook bundle install task sidekiq pro & ent gem get 401 error when upgrade ruby from 3.1.2 to 3.2.2

### ISSUE THREAD

**Issue by Leoyang0717** [sidekiq/sidekiq#5976]
Ruby version: upgrade from 3.1.2 to 3.2.2
Rails version: 7.0.5
Sidekiq / Pro / Enterprise version(s): Enterprise

I want upgrade AWS bastion ruby version, use ansible playbook to update.
but when I run `bundle install` task, I got this error message

```
fatal: [stg-server01]: FAILED! => {"changed": false, "cmd": "/opt/ruby-3.2.2/bin/bundle install --gemfile /srv/app/current/Gemfile",
 "msg": "Retrying download gem from https://enterprise.contribsys.com/ due to error (2/4): Gem::RemoteFetcher::FetchError bad 
 response Unauthorized 401 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)\nRetrying download gem from 
 https://enterprise.contribsys.com/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 (
 https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)\nRetrying download gem from https://enterprise.contribsys.com/ 
 due to error (4/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)\nBundler::HTTPError: Could not download gem 
 from\nhttps://enterprise.contribsys.com/ due to underlying error <bad response\nUnauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)>\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/rubygems_integration.rb:508:in\n`rescue in download_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/rubygems_integration.rb:480:in\n`download_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:527:in\n`download_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:479:in\n`fetch_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:165:in\n`install'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/gem_installer.rb:54:in\n`install'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/gem_installer.rb:16:in\n`install_from_spec'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/parallel_installer.rb:186:in\n`do_install'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/parallel_installer.rb:177:in\n`block in worker_pool'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:62:in\n`apply_func'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:57:in\n`block in process_queue'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:54:in\n`loop'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:54:in\n`process_queue'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:91:in\n`block (2 levels) in create_threads'\n\nAn error occurred while installing sidekiq-pro (7.1.3), and 
 Bundler cannot\ncontinue.\n\nIn Gemfile:\n  sidekiq-ent was resolved to 7.1.1, which depends on\n    sidekiq-pro", "rc": 5, "stderr": 
 "Retrying download gem from https://enterprise.contribsys.com/ due to error (2/4): Gem::RemoteFetcher::FetchError bad 
 response Unauthorized 401 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)\nRetrying download gem from 
 https://enterprise.contribsys.com/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)\nRetrying download gem from https://enterprise.contribsys.com/ 
 due to error (4/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)\nBundler::HTTPError: Could not download gem 
 from\nhttps://enterprise.contribsys.com/ due to underlying error <bad response\nUnauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)>\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/rubygems_integration.rb:508:in\n`rescue in download_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/rubygems_integration.rb:480:in\n`download_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:527:in\n`download_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:479:in\n`fetch_gem'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:165:in\n`install'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/gem_installer.rb:54:in\n`install'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/gem_installer.rb:16:in\n`install_from_spec'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/parallel_installer.rb:186:in\n`do_install'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/parallel_installer.rb:177:in\n`block in worker_pool'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:62:in\n`apply_func'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:57:in\n`block in process_queue'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:54:in\n`loop'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:54:in\n`process_queue'\n/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:91:in\n`block (2 levels) in create_threads'\n\nAn error occurred while installing sidekiq-pro (7.1.3), and 
 Bundler cannot\ncontinue.\n\nIn Gemfile:\n  sidekiq-ent was resolved to 7.1.1, which depends on\n    sidekiq-pro\n", "stderr_lines": 
 ["Retrying download gem from https://enterprise.contribsys.com/ due to error (2/4): Gem::RemoteFetcher::FetchError bad 
 response Unauthorized 401 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)", "Retrying download gem from 
 https://enterprise.contribsys.com/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)", "Retrying download gem from https://enterprise.contribsys.com/ 
 due to error (4/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)", "Bundler::HTTPError: Could not download gem from", 
 "https://enterprise.contribsys.com/ due to underlying error <bad response", "Unauthorized 401 
 (https://enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem)>", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/rubygems_integration.rb:508:in", "`rescue in download_gem'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/rubygems_integration.rb:480:in", "`download_gem'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:527:in", "`download_gem'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:479:in", "`fetch_gem'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/source/rubygems.rb:165:in", "`install'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/gem_installer.rb:54:in", "`install'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/gem_installer.rb:16:in", "`install_from_spec'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/parallel_installer.rb:186:in", "`do_install'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/installer/parallel_installer.rb:177:in", "`block in worker_pool'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:62:in", "`apply_func'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:57:in", "`block in process_queue'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-
 2.3.7/lib/bundler/worker.rb:54:in", "`loop'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in", 
 "`process_queue'", "/srv/app/shared/bundle/ruby/3.2/gems/bundler-2.3.7/lib/bundler/worker.rb:91:in", "`block (2 levels) in 
 create_threads'", "", "An error occurred while installing sidekiq-pro (7.1.3), and Bundler cannot", "continue.", "", "In Gemfile:", "  
 sidekiq-ent was resolved to 7.1.1, which depends on", "    sidekiq-pro"],
```

but I set bundle config already and if not upgrade ruby version,use capistrano deploy branch and run bundle install thats no problem.
```
BUNDLE_ENTERPRISE__CONTRIBSYS__COM="<username>:<password>"

[app-user@stg-server01 etc]$ bundle config
Settings are listed in order of priority. The top value will be used.
enterprise.contribsys.com
Set via BUNDLE_ENTERPRISE__CONTRIBSYS__COM: "<username>:[REDACTED]"
```

and test curl is 200 ok
```
curl -I https://<username>:<password>@enterprise.contribsys.com/gems/sidekiq-ent-7.1.1.gem
HTTP/1.1 200 OK
Date: Wed, 19 Jul 2023 04:54:05 GMT
Server: Apache/2.4.52 (Ubuntu)
Last-Modified: Wed, 07 Jun 2023 14:24:35 GMT
Accept-Ranges: bytes
Content-Length: 120832

curl -I https://<username>:<password>@enterprise.contribsys.com/gems/sidekiq-pro-7.1.3.gem
HTTP/1.1 200 OK
Date: Wed, 19 Jul 2023 05:33:49 GMT
Server: Apache/2.4.52 (Ubuntu)
Last-Modified: Thu, 01 Jun 2023 17:10:44 GMT
Accept-Ranges: bytes
Content-Length: 41472
```

```
# ansible playbook.yml
---
- hosts: all
  become: yes
  roles:
    - hostname
    - kernel
    - clock_setting
    - make_swap
    - yum_install_commons
    - history_timestamp
    - compile_env
    - vim_settings
    - ruby
    - app_user
    - application
    - bundle_install
```
```
---
# roles/application/tasks/main.yml

- name: yum install mysql2(gem) dependencies
  yum:
    name: ['mysql','mysql-devel']
    state: latest
    lock_timeout: 10

- name: gem install mysql2
  gem:
    name: mysql2
    version: 0.5.5
    executable: "{{ ruby.location }}/bin/gem"
    user_install: no

- name: gem install bundler
  gem:
    name: bundler
    version: 2.4.16
    executable: "{{ ruby.location }}/bin/gem"
    user_install: no

- name: create dir applicaton /srv/app
  file:
    dest: /srv/app
    owner: app-user
    group: app-user
    mode: 0755
    state: directory

- name: set env at /etc/default/app
  template:
    src:   app.env.j2
    dest:  /etc/default/app
    owner: root
    group: root
    mode:  0644

- name: set /etc/profile.d/app.sh
  template:
    src:   app.sh.j2
    dest:  /etc/profile.d/app.sh
    owner: root
    group: root
    mode:  0644
```
```
# roles/bundle_install/tasks/main.yml

- name: bundle install
  bundler:
    state: present
    executable: "{{ ruby.location }}/bin/bundle"
    gemfile: /srv/app/current/Gemfile
  become: true
  become_user: app-user

- name: set owner and group shared/bundle/ruby
  file:
    dest: "/srv/app/shared/bundle/ruby/{{ ruby.version.minor }}"
    owner: app-user
    group: app-user
    state: directory
    recurse: yes
```

```
# Gemfile
...
gem "sidekiq", "< 8"
source "https://enterprise.contribsys.com/" do
  gem "sidekiq-pro", "< 8"
  gem "sidekiq-ent", "< 8"
end
...
```
