### ISSUE TITLE
Why is Sidekiq ignoring the url option within a Redis sentinel configuration?

### ISSUE THREAD

**Issue by lu-x** [sidekiq/sidekiq#6276]
I'm not sure if this is the right place to ask, feel free to close the issue if it's misplaced here.

I recently tried to use Sidekiq with a Redis Sentinel cluster and added the configuration to my application. I also want to use a different database than the default (0).
I realized that Sidekiq ignores the database if i try to set it with the url option. In fact, it seems to ignore the complete url option (https://github.com/sidekiq/sidekiq/blob/30786e082c70349ab27ffa9eccc42fb0c696164d/lib/sidekiq/redis_client_adapter.rb#L99).

In the [upgrade guide](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-API-Migration.md#redis-sentinels) there's a link to the redis-client documentation which states that it's possible to set the db with the url.

Example:
```yaml
# doesn't work:
sidekiq:
  url: "redis://mymain/12"
  password: ..
  name: mymain
  sentinels:
    - host: ..  
      port: ..
      password: ..
    - host: ..
      port: ..
      password: ..
    - host: ..
      port: ..
      password: ..
  role: master

# works
sidekiq:
  db: 12
  password: ..
  name: mymain
  sentinels:
    - host: ..  
      port: ..
      password: ..
    - host: ..
      port: ..
      password: ..
    - host: ..
      port: ..
      password: ..
  role: master
```

If my assumption is correct: is there a reason why Sidekiq ignores the option? It'd be very good to include this in the documentation then.
