### ISSUE TITLE
Consolidate metrics under the sidekiq.* namespace

### ISSUE THREAD

**Issue by weppos** [sidekiq/sidekiq#6337]
Ruby version: -
Rails version: -
Sidekiq / Pro / Enterprise version(s): 7.x

[Sidekiq Pro sends metrics](https://github.com/sidekiq/sidekiq/wiki/Pro-Metrics) under the following namespaces:

```
sidekiq.*
jobs.*
batches.*
leader.election
```

This behavior is undesirable as, when blended into a large organization account, you can easily miss metrics. There are options to namespace the metrics, but the namespace is applied to all metrics.

So for instance, if I set the `"sidekiq"` namespace, as it follows:

```
config.dogstatsd = -> { Datadog::Statsd.new("1.2.3.4", "8125", namespace: "sidekiq") }
```

I will obtain the following:

```
sidekiq.sidekiq.*
sidekiq.jobs.*
sidekiq.batches.*
sidekiq.leader.election
```

Ideally, all metrics are reported under a consistent `"sidekiq"` prefix. Adjusting the namespace will pre-pend the prefix.

After some internal configuration, we obtained something similar applying a namespace, and remapping "sidekiq.sidekiq.*" block to "sidekiq.*".

<img width="726" alt="Screenshot 2024-06-20 at 10 30 33" src="https://github.com/sidekiq/sidekiq/assets/5387/9aaf54ed-4b37-4145-a411-8a7689c42b3e">

**Comment by javierjulio** [comment]
@weppos I'm dealing with the same situation setting up metrics and I was curious what you are using currently for the `namespace:` keyword argument in the `Datadog::Statsd` instance? Did you end up using `namespace: "sidekiq.my-app"` to get things working?

**Comment by javierjulio** [comment]
Worth noting that in the [Datadog documentation for updating the Agent configuration file](https://docs.datadoghq.com/integrations/sidekiq/#configuration) it does suggest matching against a "sidekiq.sidekiq." style prefix so that may have to be changed.

```
# dogstatsd_mapper_cache_size: 1000  # default to 1000
dogstatsd_mapper_profiles:
  - name: sidekiq
    prefix: "sidekiq."
    mappings:
      - match: 'sidekiq\.sidekiq\.(.*)'
        match_type: "regex"
        name: "sidekiq.$1"
      - match: 'sidekiq\.jobs\.(.*)\.perform'
        name: "sidekiq.jobs.perform"
        match_type: "regex"
        tags:
          worker: "$1"
      - match: 'sidekiq\.jobs\.(.*)\.(count|success|failure)'
        name: "sidekiq.jobs.worker.$2"
        match_type: "regex"
        tags:
          worker: "$1"
```
