### ISSUE TITLE
Periodic jobs stop running until sidekiq is restarted

### ISSUE THREAD

**Issue by caleb** [sidekiq/sidekiq#6422]
Ruby version: 3.3.0
Rails version: 7.1.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.2.4 / Pro 7.2.1 / Ent 7.2.4

On 8/24/2024 sidekiq ent did get updated from 7.2.2 to 7.2.4, but it doesn't seem that anything was fixed after that that might cause this, so maybe downgrading would be a solution for now.

```yaml
---
:verbose: false
:concurrency: 4

:timeout: 30

:queues:
- default
- mailers
- active_storage_analysis
- active_storage_purge
- file_upload

production:
  :concurrency: 6
staging:
  :concurrency: 6
development:
  :concurrency: 6
```

```ruby
require_relative "../../app/lib/mojo_sidekiq/current_user_middleware"

Sidekiq::Enterprise.unique! unless Rails.env.test?
Sidekiq.default_job_options = { "backtrace" => true }
Sidekiq.configure_server do |config|
  config.super_fetch!

  if Rails.env.production?
    require_relative "../periodic_jobs"
    config.periodic(&PERIODIC_JOBS)
  end

  config.capsule("single-threaded") do |cap|
    cap.concurrency = 1
    cap.queues = %w[serial]
  end

  config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new

  config.client_middleware do |chain|
    chain.add Sidekiq::Debouncer::Middleware::Client
    chain.add MojoSidekiq::CurrentUserMiddleware::Client
  end

  config.server_middleware do |chain|
    chain.add Sidekiq::Debouncer::Middleware::Server
    chain.add MojoSidekiq::CurrentUserMiddleware::Server
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Debouncer::Middleware::Client
    chain.add MojoSidekiq::CurrentUserMiddleware::Client
  end
end
```

Here's the backtrace from GDB: https://gist.github.com/caleb/0aaf227b1435bd55f3347290d550c5b9

It seems that jobs that are created in our app are run, and there aren't any jobs in the "scheduled" tab or in the "busy" tab.

If you see anything in my config or backtrace that are red flags let me know.
